/**
 * Runs in the page (main world), injected by the manifest itself so that it
 * executes before the site's own bundle — the player fetches its source as
 * soon as it mounts, long before `document_idle`.
 *
 * The stream url only exists behind a `kkey` token generated by the site's
 * obfuscated JS, so instead of recomputing it we observe the response the
 * player already receives.
 */
const MARKER = '__kisskhExtVideoHook__';

/** Fields the player has used over time to carry the stream url. */
const SOURCE_FIELD = /^(Video|link|dataSaver|ThirdParty)$/i;
const MEDIA_URL = /\.(m3u8|mpd|mp4)(\?|$)/i;

/**
 * The payload shape keeps changing, so rather than reading fixed keys we walk
 * it and take the first thing that either sits under a known field name or
 * simply looks like a media url.
 */
function extract(data: unknown): string | null {
  const stack: unknown[] = [data];
  const seen = new Set<unknown>();
  while (stack.length) {
    const node = stack.pop();
    if (!node || typeof node !== 'object' || seen.has(node)) continue;
    seen.add(node);
    if (Array.isArray(node)) {
      stack.push(...node);
      continue;
    }
    for (const [key, value] of Object.entries(node)) {
      if (typeof value === 'string' && /^https?:/i.test(value)) {
        if (SOURCE_FIELD.test(key) || MEDIA_URL.test(value)) return value;
      } else if (value && typeof value === 'object') {
        stack.push(value);
      }
    }
  }
  return null;
}

export default defineContentScript({
  matches: [
    '*://kisskh.co/*',
    '*://*.kisskh.co/*',
    '*://kisskh.me/*',
    '*://*.kisskh.me/*',
  ],
  world: 'MAIN',
  runAt: 'document_start',
  allFrames: true,
  main() {
    const win = window as unknown as Record<string, unknown>;
    if (win[MARKER]) return;
    win[MARKER] = true;

    const sent = new Set<string>();
    const report = (data: unknown) => {
      const url = extract(data);
      if (!url || sent.has(url)) return;
      sent.add(url);
      window.postMessage({ source: 'kisskh-ext', type: 'video', url }, '*');
    };

    const originalFetch = window.fetch;
    window.fetch = function (this: unknown, ...args: Parameters<typeof fetch>) {
      const promise = originalFetch.apply(this as never, args);
      promise
        .then((res) => {
          if (!res?.ok) return;
          const type = res.headers.get('content-type') ?? '';
          // The episode source endpoint ends in `.png` but answers JSON.
          if (!/json/i.test(type) && !/\.png(\?|$)/i.test(res.url)) return;
          res.clone().json().then(report).catch(() => {});
        })
        .catch(() => {});
      return promise;
    } as typeof fetch;

    const send = XMLHttpRequest.prototype.send;
    XMLHttpRequest.prototype.send = function (this: XMLHttpRequest, ...args: unknown[]) {
      this.addEventListener('load', () => {
        if (this.status !== 200) return;
        try {
          report(JSON.parse(this.responseText));
        } catch {
          // Not JSON; nothing to read.
        }
      });
      return (send as (...a: unknown[]) => void).apply(this, args);
    } as typeof send;
  },
});
